[0m[1;104m [0m[1;97m add:add_numbers [0m[1;33m [5 tests] [0m
[0m[1;44m [0m[0;97m [1/5] add:add_numbers [0m  [0m[0;32mOK [0 of 1 failed][0m
[0m[1;44m [0m[0;97m [2/5] add:add_numbers [0m  [0m[0;32mOK [0 of 1 failed][0m
[0m[1;44m [0m[0;97m [3/5] add:add_numbers [0m  [0m[0;32mOK [0 of 1 failed][0m
[0m[1;44m [0m[0;97m [4/5] add:add_numbers [0m  [0m[0;32mOK [0 of 1 failed][0m
[0m[1;44m [0m[0;97m [5/5] add:add_numbers [0m  [0m[0;32mOK [0 of 1 failed][0m

[0m[0;32mAll tests passed [0 of 5 failed][0m

