name: Integration & unit tests

on: [push]

jobs:
  builld_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install gcc-multilib g++

    - name: Build and run tests
      run: |
        cd ${{github.workspace}}
        bash ./tests/run_all_tests.sh || exit
